name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: main
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        working-directory: main
        run: |
          pytest -q

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        working-directory: main
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/flask-lab-app:${{ github.sha }} -t ${{ secrets.DOCKER_HUB_USERNAME }}/flask-lab-app:latest .

      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        working-directory: main
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/flask-lab-app:${{ github.sha }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/flask-lab-app:latest
